version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - 5432:5432
  web:
    image: app:latest
    ports:
        - "8080:8080"
    volumes:
        - ./backend:/go/src/github.com/griggsca91/sideproject/app