version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
      - 5432:5432
  web:
    build: .
    command: /app/main
    ports:
        - "8000:8080"